version: '3.8'
services:
  mysql:
    image: mysql:latest
    container_name: databaseUsers
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: users
      MYSQL_USER: admin
      MYSQL_PASSWORD: 1234
    ports:
      - "3308:3306"
